logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8080
spring:
  application:
    name: authserver
  thymeleaf:
    cache: false
  security:
    user: 
      password: password