logging:
  level:
    org.springframework.security: DEBUG
server:
  servlet:
    contextPath: /uaa
  port: 8080
management:
  security:
    enabled: false
spring:
  application:
    name: authserver
  thymeleaf:
    cache: false