author:
  name: kxx
  
spring:
  thymeleaf:
    cache: false
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.207:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qwe123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      pool-name: blah
  data:
    jpa:
      repositories:
        enabled: true
